-- ReLoop core schema
-- All identifiers are UUIDs generated by the application; public pickup codes (RL-XXXXXX)
-- are random and carry a UNIQUE constraint.

CREATE TABLE users (
    id              UUID PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    email_verified  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at   TIMESTAMPTZ,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT users_role_check   CHECK (role IN ('USER', 'COLLECTOR', 'ADMIN')),
    CONSTRAINT users_status_check CHECK (status IN ('ACTIVE', 'DISABLED'))
);

CREATE TABLE user_profiles (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL UNIQUE REFERENCES users (id) ON DELETE CASCADE,
    full_name   VARCHAR(120) NOT NULL,
    phone       VARCHAR(20),
    city        VARCHAR(80),
    address     VARCHAR(255),
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE refresh_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    revoked_at  TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);

CREATE TABLE password_reset_tokens (
    id          UUID PRIMARY KEY,
    user_id     UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash  VARCHAR(64) NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    used_at     TIMESTAMPTZ,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_password_reset_tokens_user ON password_reset_tokens (user_id);

CREATE TABLE waste_categories (
    id                            UUID PRIMARY KEY,
    code                          VARCHAR(30) NOT NULL UNIQUE,
    name                          VARCHAR(80) NOT NULL,
    description                   VARCHAR(500),
    color_hex                     VARCHAR(9),
    default_disposal_instructions VARCHAR(1000),
    is_active                     BOOLEAN NOT NULL DEFAULT TRUE,
    created_at                    TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE waste_scans (
    id                  UUID PRIMARY KEY,
    user_id             UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id         UUID REFERENCES waste_categories (id),
    image_url           TEXT,
    detected_item       VARCHAR(200),
    confidence          NUMERIC(4, 3) CHECK (confidence IS NULL OR (confidence BETWEEN 0 AND 1)),
    recyclable          BOOLEAN,
    hazardous           BOOLEAN,
    disposal_instruction VARCHAR(1000),
    source              VARCHAR(10) NOT NULL,
    ai_model            VARCHAR(60),
    raw_response        TEXT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT waste_scans_source_check CHECK (source IN ('AI', 'MANUAL'))
);

CREATE INDEX idx_waste_scans_user ON waste_scans (user_id);
CREATE INDEX idx_waste_scans_created_at ON waste_scans (created_at);

CREATE TABLE collection_partners (
    id                  UUID PRIMARY KEY,
    user_id             UUID REFERENCES users (id) ON DELETE SET NULL,
    organization_name   VARCHAR(160) NOT NULL,
    contact_person      VARCHAR(120) NOT NULL,
    phone               VARCHAR(20)  NOT NULL,
    email               VARCHAR(255),
    address             VARCHAR(255) NOT NULL,
    city                VARCHAR(80)  NOT NULL,
    pincode             VARCHAR(12),
    operating_hours     VARCHAR(200),
    registration_number VARCHAR(80),
    document_urls       TEXT,
    status              VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    rejection_reason    VARCHAR(500),
    verified_at         TIMESTAMPTZ,
    verified_by         UUID REFERENCES users (id),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT collection_partners_status_check CHECK (status IN ('PENDING', 'VERIFIED', 'REJECTED'))
);

CREATE INDEX idx_collection_partners_status ON collection_partners (status);
CREATE INDEX idx_collection_partners_user ON collection_partners (user_id);

CREATE TABLE collection_partner_materials (
    partner_id  UUID NOT NULL REFERENCES collection_partners (id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES waste_categories (id),
    PRIMARY KEY (partner_id, category_id)
);

CREATE TABLE collection_points (
    id              UUID PRIMARY KEY,
    name            VARCHAR(160) NOT NULL,
    address         VARCHAR(255) NOT NULL,
    city            VARCHAR(80)  NOT NULL,
    pincode         VARCHAR(12),
    latitude        NUMERIC(9, 6) NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude       NUMERIC(9, 6) NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    operating_hours VARCHAR(200),
    contact_phone   VARCHAR(20),
    is_verified     BOOLEAN NOT NULL DEFAULT FALSE,
    source          VARCHAR(20) NOT NULL DEFAULT 'ADMIN',
    partner_id      UUID REFERENCES collection_partners (id) ON DELETE SET NULL,
    created_by      UUID REFERENCES users (id),
    is_active       BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT collection_points_source_check CHECK (source IN ('ADMIN', 'COLLECTOR', 'IMPORT'))
);

CREATE INDEX idx_collection_points_city ON collection_points (city);
CREATE INDEX idx_collection_points_active ON collection_points (is_active);
CREATE INDEX idx_collection_points_geo ON collection_points (latitude, longitude);

CREATE TABLE collection_point_materials (
    point_id    UUID NOT NULL REFERENCES collection_points (id) ON DELETE CASCADE,
    category_id UUID NOT NULL REFERENCES waste_categories (id),
    PRIMARY KEY (point_id, category_id)
);

CREATE TABLE pickup_requests (
    id                    UUID PRIMARY KEY,
    code                  VARCHAR(16) NOT NULL UNIQUE,
    user_id               UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    collector_id          UUID REFERENCES collection_partners (id),
    category_id           UUID NOT NULL REFERENCES waste_categories (id),
    estimated_quantity_kg NUMERIC(8, 2) NOT NULL CHECK (estimated_quantity_kg > 0),
    actual_quantity_kg    NUMERIC(8, 2) CHECK (actual_quantity_kg IS NULL OR actual_quantity_kg > 0),
    address               VARCHAR(255) NOT NULL,
    city                  VARCHAR(80)  NOT NULL,
    pincode               VARCHAR(12),
    latitude              NUMERIC(9, 6),
    longitude             NUMERIC(9, 6),
    pickup_date           DATE NOT NULL,
    time_slot             VARCHAR(20) NOT NULL,
    photo_url             TEXT,
    notes                 VARCHAR(1000),
    status                VARCHAR(20) NOT NULL DEFAULT 'REQUESTED',
    scheduled_at          TIMESTAMPTZ,
    accepted_at           TIMESTAMPTZ,
    picked_up_at          TIMESTAMPTZ,
    processing_at         TIMESTAMPTZ,
    recovered_at          TIMESTAMPTZ,
    cancelled_at          TIMESTAMPTZ,
    cancel_reason         VARCHAR(500),
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT pickup_requests_status_check
        CHECK (status IN ('REQUESTED', 'ACCEPTED', 'SCHEDULED', 'PICKED_UP', 'PROCESSING', 'RECOVERED', 'CANCELLED')),
    CONSTRAINT pickup_requests_slot_check CHECK (time_slot IN ('MORNING', 'AFTERNOON', 'EVENING'))
);

CREATE INDEX idx_pickup_requests_user ON pickup_requests (user_id);
CREATE INDEX idx_pickup_requests_collector ON pickup_requests (collector_id);
CREATE INDEX idx_pickup_requests_status ON pickup_requests (status);

CREATE TABLE collected_waste (
    id                UUID PRIMARY KEY,
    pickup_request_id UUID NOT NULL UNIQUE REFERENCES pickup_requests (id) ON DELETE CASCADE,
    collector_id      UUID NOT NULL REFERENCES collection_partners (id),
    user_id           UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    category_id       UUID NOT NULL REFERENCES waste_categories (id),
    quantity_kg       NUMERIC(8, 2) NOT NULL CHECK (quantity_kg > 0),
    collection_date   TIMESTAMPTZ NOT NULL,
    notes             VARCHAR(500),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_collected_waste_user ON collected_waste (user_id);
CREATE INDEX idx_collected_waste_category ON collected_waste (category_id);
CREATE INDEX idx_collected_waste_date ON collected_waste (collection_date);

CREATE TABLE notifications (
    id           UUID PRIMARY KEY,
    user_id      UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    title        VARCHAR(160) NOT NULL,
    message      VARCHAR(1000) NOT NULL,
    type         VARCHAR(30) NOT NULL,
    reference_id UUID,
    is_read      BOOLEAN NOT NULL DEFAULT FALSE,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user ON notifications (user_id, is_read);
