-- Reference data: waste categories used for classification, collection filtering,
-- and impact reporting. This is taxonomy, NOT activity data.

INSERT INTO waste_categories (id, code, name, description, color_hex, default_disposal_instructions) VALUES
(gen_random_uuid(), 'PLASTIC', 'Plastic',
 'Plastic containers, bottles, packaging and rigid plastics.',
 '#2D6A4F',
 'Empty, rinse and dry containers. Separate caps where required. Place in the plastic recycling stream.'),
(gen_random_uuid(), 'PAPER', 'Paper',
 'Newspaper, office paper, magazines and clean paper products.',
 '#40916C',
 'Keep paper clean and dry. Flatten boxes and remove plastic windows or tape where possible.'),
(gen_random_uuid(), 'CARDBOARD', 'Cardboard',
 'Corrugated boxes and cartons.',
 '#588157',
 'Flatten boxes and keep them dry. Remove excessive tape and staples.'),
(gen_random_uuid(), 'METAL', 'Metal',
 'Aluminium cans, steel tins and clean scrap metal.',
 '#52796F',
 'Rinse cans and tins. Do not mix with hazardous or food-soiled waste.'),
(gen_random_uuid(), 'GLASS', 'Glass',
 'Glass bottles and jars.',
 '#84A98C',
 'Rinse jars and bottles. Handle broken glass with care and wrap it securely if disposal is required.'),
(gen_random_uuid(), 'E_WASTE', 'E-waste',
 'Electronic devices, cables, batteries and appliances.',
 '#354F52',
 'Never discard with general waste. Take to a certified e-waste collection point; wipe personal data from devices.'),
(gen_random_uuid(), 'HAZARDOUS', 'Hazardous',
 'Paints, solvents, chemicals, pesticides, medical waste and fluorescent tubes.',
 '#9B2226',
 'Do not open, mix or burn. Store in original containers where possible and hand over at a hazardous waste facility only.'),
(gen_random_uuid(), 'ORGANIC', 'Organic',
 'Food scraps, garden waste and compostable material.',
 '#76C893',
 'Compost where possible or use the organic waste stream. Keep free of plastic and metal.'),
(gen_random_uuid(), 'TEXTILE', 'Textile',
 'Clothing, fabrics, shoes and bags.',
 '#A5A58D',
 'Donate wearable items. Damaged textiles belong in dedicated textile collection, not general waste.'),
(gen_random_uuid(), 'OTHER', 'Other',
 'Mixed or unusual items that do not fit a standard category.',
 '#6B705C',
 'Identify the dominant material and follow its disposal guidance, or ask a verified collector.');
